//  fetchBalances
export const VAULT_FETCH_BALANCES_BEGIN = 'VAULT_FETCH_BALANCES_BEGIN';
export const VAULT_FETCH_BALANCES_SUCCESS = 'VAULT_FETCH_BALANCES_SUCCESS';
export const VAULT_FETCH_BALANCES_FAILURE = 'VAULT_FETCH_BALANCES_FAILURE';
export const VAULT_FETCH_BALANCES_DISMISS_ERROR = 'VAULT_FETCH_BALANCES_DISMISS_ERROR';
//  fetchPoolBalances
export const VAULT_FETCH_POOL_BALANCES_BEGIN = 'VAULT_FETCH_POOL_BALANCES_BEGIN';
export const VAULT_FETCH_POOL_BALANCES_SUCCESS = 'VAULT_FETCH_POOL_BALANCES_SUCCESS';
export const VAULT_FETCH_POOL_BALANCES_FAILURE = 'VAULT_FETCH_POOL_BALANCES_FAILURE';
export const VAULT_FETCH_POOL_BALANCES_DISMISS_ERROR = 'VAULT_FETCH_POOL_BALANCES_DISMISS_ERROR';
//  fetchApproval
export const VAULT_FETCH_APPROVAL_BEGIN = 'VAULT_FETCH_APPROVAL_BEGIN';
export const VAULT_FETCH_APPROVAL_SUCCESS = 'VAULT_FETCH_APPROVAL_SUCCESS';
export const VAULT_FETCH_APPROVAL_FAILURE = 'VAULT_FETCH_APPROVAL_FAILURE';
export const VAULT_FETCH_APPROVAL_DISMISS_ERROR = 'VAULT_FETCH_APPROVAL_DISMISS_ERROR';
//  fetchDeposit
export const VAULT_FETCH_DEPOSIT_BEGIN = 'VAULT_FETCH_DEPOSIT_BEGIN';
export const VAULT_FETCH_DEPOSIT_SUCCESS = 'VAULT_FETCH_DEPOSIT_SUCCESS';
export const VAULT_FETCH_DEPOSIT_FAILURE = 'VAULT_FETCH_DEPOSIT_FAILURE';
export const VAULT_FETCH_DEPOSIT_DISMISS_ERROR = 'VAULT_FETCH_DEPOSIT_DISMISS_ERROR';
//  fetchClaim
export const VAULT_FETCH_CLAIM_BEGIN = 'VAULT_FETCH_CLAIM_BEGIN';
export const VAULT_FETCH_CLAIM_SUCCESS = 'VAULT_FETCH_CLAIM_SUCCESS';
export const VAULT_FETCH_CLAIM_FAILURE = 'VAULT_FETCH_CLAIM_FAILURE';
export const VAULT_FETCH_CLAIM_DISMISS_ERROR = 'VAULT_FETCH_CLAIM_DISMISS_ERROR';
//  fetchWithdraw
export const VAULT_FETCH_WITHDRAW_BEGIN = 'VAULT_FETCH_WITHDRAW_BEGIN';
export const VAULT_FETCH_WITHDRAW_SUCCESS = 'VAULT_FETCH_WITHDRAW_SUCCESS';
export const VAULT_FETCH_WITHDRAW_FAILURE = 'VAULT_FETCH_WITHDRAW_FAILURE';
export const VAULT_FETCH_WITHDRAW_DISMISS_ERROR = 'VAULT_FETCH_WITHDRAW_DISMISS_ERROR';
