//  fetchBalances
export const VAULT_FETCH_BALANCES_BEGIN = 'VAULT_FETCH_BALANCES_BEGIN';
export const VAULT_FETCH_BALANCES_SUCCESS = 'VAULT_FETCH_BALANCES_SUCCESS';
export const VAULT_FETCH_BALANCES_FAILURE = 'VAULT_FETCH_BALANCES_FAILURE';
export const VAULT_FETCH_BALANCES_DISMISS_ERROR = 'VAULT_FETCH_BALANCES_DISMISS_ERROR';
//  fetchPoolBalances
export const VAULT_FETCH_POOL_BALANCES_BEGIN = 'VAULT_FETCH_POOL_BALANCES_BEGIN';
export const VAULT_FETCH_POOL_BALANCES_SUCCESS = 'VAULT_FETCH_POOL_BALANCES_SUCCESS';
export const VAULT_FETCH_POOL_BALANCES_FAILURE = 'VAULT_FETCH_POOL_BALANCES_FAILURE';
export const VAULT_FETCH_POOL_BALANCES_DISMISS_ERROR = 'VAULT_FETCH_POOL_BALANCES_DISMISS_ERROR';
